Mean of simulation solution
juliohm/GeoStatsDevTools.jl pull request #2
Opened 2018-12-05 10:53 UTC by riyadm

Just a raw sketch, any feedback highly appreciated!

2018-12-06 09:47 UTC, juliohm requested changes
Thanks for the addition! The code is looking great. I've requested some minor modifications before we can keep working on it. Please let me know if you have any questions.

Also, could you please fix the indentation to be 2 spaces to be consistent with the rest of the code?

After you make the changes, I think the next thing is to add some tests for statistics. You could create a file called `statistics.jl` under the `test` folder and write some basic tests of what the statistic should be for very simple solution objects that you construct manually.

2018-12-06 09:47 UTC, juliohm commented on src/GeoStatsDevTools.jl
> +using Statistics
Do we need to use Statistics or just import it as below?

2018-12-06 09:47 UTC, juliohm commented on src/statistics.jl
> +Mean(domain, values) = Mean{typeof(domain)}(domain, values)
I think we could eliminate this external constructor, and call the internal one in the constructor that takes a solution. See below.

2018-12-06 09:47 UTC, juliohm commented on src/statistics.jl
> +    Mean(solution.domain, values)
Here you could call the internal constructor `Mean{typeof(sdomain)}(sdomain, values)`

2018-12-06 09:47 UTC, juliohm commented on src/statistics.jl
> +    values = Dict(var => mean(solution.realizations[var]) for var in variables)
You could eliminate `variables` and loop the `key,val` pairs of the `realizations` dictionary:

```julia
values = Dict(var => mean(real) for (var,real) in solution.realizations)
```

2018-12-06 09:47 UTC, juliohm commented on src/statistics.jl
> +function digest(statistic::Mean{<:RegularGrid})
Let's think about `digest` later, I think we could eliminate it from this PR for now.

2018-12-18 13:03 UTC, juliohm commented on src/GeoStatsDevTools.jl
> +
Please erase this white space change :+1:

2018-12-18 13:03 UTC, juliohm commented on src/GeoStatsDevTools.jl
> +import Statistics: mean, quantile, var
Nice

2018-12-18 13:05 UTC, juliohm commented on src/GeoStatsDevTools.jl
> +#post processing
Try to follow the code conventions, I might be picky, but there is a reason for that :)

In this case, please add a whitespace after the `#` and erase extra blank lines, only one blank line dividing concepts.

2018-12-18 13:05 UTC, juliohm commented on src/GeoStatsDevTools.jl
> +
Same here, too many blank lines

2018-12-18 13:06 UTC, juliohm commented on src/GeoStatsDevTools.jl
> +  #re-export statistics
white space after `#`

2018-12-18 13:08 UTC, juliohm commented on src/statistics.jl
> +  values::Dict{Symbol, Vector}
Erase white space after the comma here, and all other occurrences

2018-12-18 13:09 UTC, juliohm commented on src/statistics.jl
> +struct Quantile{D<:AbstractDomain, P<:Real}
I don't think we need  to generalize on `P`, we can always use `Float64` so this type parameter is not necessary. It is making the quantile type inconsistent with the other types that are only parameterized by `D`.

2018-12-18 13:09 UTC, juliohm commented on src/statistics.jl
> +  p::P
p::Float64

2018-12-18 13:14 UTC, juliohm commented on src/statistics.jl
> +  values = Dict(var => quantile.(slices(real), p) for (var, real) in solution.realizations)
I think we should be clearer here, the code is not easy to read. Maybe we should do an explicit loop over `solution.realizations` and for each entry perform the quantile calculation. I can work on this after you write some tests. :+1:

2018-12-18 13:15 UTC, juliohm commented on src/statistics.jl
> +quantile(solution::SimulationSolution, ps::AbstractArray) = [quantile(solution, p) for p in ps]
ps::AbstractVector{Real}

2018-12-18 13:18 UTC, juliohm commented on src/statistics.jl
> +# IO methods
Notice that all IO methods are the same except that they are dispatching on specific subtypes. You can replace all of them by a single method that takes a `AbstractStatistic` instead and Julia will take care of the rest.

Please print `Quantile` like the other statistics, no need to print the value of `p`. I am also not sure we need to store `p` in the object, it seems not that useful.

2018-12-18 13:19 UTC, juliohm commented
Cool stuff, please check the comments, we are almost there for a first merge :)

2018-12-21 10:16 UTC, riyadm commented
Thanks for the feedback! I kept `p` in `Quantile` object thinking it might be useful when computing quantiles for an array of probabilities, but we can remove it. Let me know what you think.

Thanks!

2018-12-21 10:17 UTC, juliohm commented
Thanks! Will take a look when I find some time 👍

On Fri, Dec 21, 2018, 08:16 Riyad Muradov <notifications@github.com wrote:

> Thanks for the feedback! I kept p in Quantile object thinking it might be
> useful when computing quantiles for an array of probabilities, but we can
> remove it. Let me know what you think.
>
> Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/juliohm/GeoStatsDevTools.jl/pull/2#issuecomment-449346745>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADMLbaQ4TY_oJeJTDGn-moo_T9rDwujaks5u7LTvgaJpZM4ZCeqU>
> .
>

2018-12-21 19:47 UTC, juliohm commented
I had the chance to take a second look into this, and noticed that we could exploit the repetitiveness of this code to refactor it. What do you think of the following?

Instead of defining an `AbstractStatistic`, we would define a concrete type:

```julia
struct SpatialStatistic{D<:AbstractDomain}
  domain::D
  values::Dict{Symbol,Vector}
end

SpatialStatistic(domain, values) = SpatialStatistic{typeof(domain)}(domain, values)
```

to represent the result of any operation like `mean`, `var` and `quantile`. Now, instead of having different types for each of these statistics, we would just implement `mean`, `var`, and `quantile` from Statistics.jl and return a `SpatialStatistic` object as the result. This way we can always talk in terms of function calls and get back the same object type for which we can define a single plot recipe and IO methods.

For example, to implement the mean, we would have:

```julia
function mean(solution::SimulationSolution)
  values = Dict(variable => mean(real) for (variable, real) in solution.realizations)
  SpatialStatistic(solution.domain, values)
end
```

Could you make these changes? Thanks for the work so far!

2018-12-28 20:25 UTC, riyadm commented
Hi, great suggestion! Do you think it would still be useful to somehow store the name of statistic in the object? Or implement`SpatialStatistic` and have subtypes for each statistic? Thanks!

2018-12-28 20:29 UTC, juliohm commented
I don't know if it would be useful. Can't see an application at the moment.
If you have something in mind let me know. I think in terms of code
repetition we don't have too many options.

On Fri, Dec 28, 2018, 18:25 Riyad Muradov <notifications@github.com wrote:

> Hi, great suggestion! Do you think it would still be useful to somehow
> store the name of statistic in the object? Or implementSpatialStatistic
> and have subtypes for each statistic? Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/juliohm/GeoStatsDevTools.jl/pull/2#issuecomment-450421803>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADMLbWoZC_9Q56yhBAdm_z3hlQL6Satfks5u9n5EgaJpZM4ZCeqU>
> .
>

2018-12-29 20:01 UTC, juliohm requested changes
Awesome! It is looking great! Thanks!

After you take care of these final comments and add the license header like in other files, I will merge and tag a new release. :)

I've erased my name from the header since it is already shown in the LICENSE file itself. You can add the following:

```
# ------------------------------------------------------------------
# Licensed under the ISC License. See LICENCE in the project root.
# ------------------------------------------------------------------
```

2018-12-29 20:01 UTC, juliohm commented on src/statistics.jl
> +  values = Dict(variable => mean(real) for (variable, real) in solution.realizations)
Could you please replace all occurrences of `real` by `reals` to make it clear that we have a vector of realizations for each variable?

2018-12-29 20:01 UTC, juliohm commented on src/statistics.jl
> +    slices = [getindex.(real, i) for i in 1:npoints(solution.domain)]
What about converting these lines into another for loop over pixels? Inside of this loop you would compute the quantile for the pixel and continue pixel by pixel instead of reserving a lot of memory at once for all pixels.

2019-01-01 20:02 UTC, juliohm approved these changes

2019-01-01 20:03 UTC, merged

2019-01-01 20:04 UTC, juliohm commented
Useful stuff! Thanks!